_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.8
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size:
    value: 64
block_size:
    value: 1024
dropout:
    value: 0.1
learning_rate:
    value: 0.0003
n_embd:
    value: 384
n_head:
    value: 6
n_layer:
    value: 6
num_gpus:
    value: 2
optimizer:
    value: 8-bit AdamW
vocab_size:
    value: 50257
